Repository mainmatter/mainmatter.com, pull requests merged in 2022-12, with the labels that each got.

#1959 Fix typo on landing page
  src/index.njk
Labels: bug

#1953 Sending Emails from the Edge with Rust
  src/posts/2022-12-09-sending-emails-from-the-edge-with-rust.md
  static/assets/images/posts/2022-12-09-sending-emails-from-the-edge-with-rust/og-image.jpg
  static/assets/images/posts/2022-12-09-sending-emails-from-the-edge-with-rust/rust-mail-server.png
Labels: blog post

#1955 Add diff-js styles
  package.json
  src/assets/css/base/_code.scss
  src/posts/2018-01-24-ember-freestyle.md
  yarn.lock
Labels: enhancement
