Repository mainmatter/mainmatter.com, pull requests merged in 2025-03, with the labels that each got.

#2581 Add EAA blog post
  src/posts/2025-03-04-making-your-web-application-compliant-with-the-european-accessibility-act.md
  static/assets/images/posts/2025-03-04-making-your-web-application-compliant-with-the-european-accessibility-act/og-image.png
Labels: blog post

#2652 Migrate scss files to @use syntax
  src/assets/css/app.scss
  src/assets/css/base/_breakpoints.scss
  src/assets/css/base/_forms.scss
  src/assets/css/base/_global.scss
  src/assets/css/base/_typography.scss
  src/assets/css/base/_utility.scss
  src/assets/css/base/_variables.scss
  src/assets/css/components/_author-header.scss
  src/assets/css/components/_author.scss
  src/assets/css/components/_cards.scss
  src/assets/css/components/_case-study.scss
  src/assets/css/components/_collection-header.scss
  src/assets/css/components/_color-hero.scss
  src/assets/css/components/_contact-form.scss
  src/assets/css/components/_cta-banner.scss
  src/assets/css/components/_embroider-sponsors.scss
  src/assets/css/components/_event-cards.scss
  src/assets/css/components/_featured-case-studies.scss
  src/assets/css/components/_featured-case-study.scss
  src/assets/css/components/_featured-services.scss
  src/assets/css/components/_footer-menu.scss
  src/assets/css/components/_footer.scss
  src/assets/css/components/_form-with-image.scss
  src/assets/css/components/_image-aspect-ratio.scss
  src/assets/css/components/_image-banner-with-text.scss
  src/assets/css/components/_images-side-by-side-grid.scss
  src/assets/css/components/_logo-list.scss
  src/assets/css/components/_mainmatter-team.scss
  src/assets/css/components/_mobile-menu.scss
  src/assets/css/components/_nav.scss
  src/assets/css/components/_open-source-list.scss
  src/assets/css/components/_policy.scss
  src/assets/css/components/_post.scss
  src/assets/css/components/_prev-next.scss
  src/assets/css/components/_quote.scss
  src/assets/css/components/_quotes-list.scss
  src/assets/css/components/_recent-posts.scss
  src/assets/css/components/_rte.scss
  src/assets/css/components/_scroll-slides.scss
  src/assets/css/components/_secondary-feature.scss
  src/assets/css/components/_split-content.scss
  src/assets/css/components/_startups.scss
  src/assets/css/components/_strategy-list.scss
  src/assets/css/components/_tag-filter.scss
  src/assets/css/components/_tags.scss
  src/assets/css/components/_talk-banner.scss
  src/assets/css/components/_talk-card.scss
  src/assets/css/components/_talks.scss
  src/assets/css/components/_text-with-list.scss
  src/assets/css/components/_work.scss
  src/assets/css/components/_workshop-authors-big.scss
  src/assets/css/mixins/_rem-calc.scss
  src/assets/css/workshop-lp.scss
Labels: technical debt

#2656 render HTML inside rss/atom feeds
  .prettierignore
  src/atom.njk
  src/feed.njk
Labels: bug

#2655 Improve blog typography
  src/assets/css/base/_prism-theme.scss
  src/assets/css/components/_post.scss
  src/assets/css/components/_rte.scss
Labels: enhancement

#2643 Gravity announcement
  src/assets/css/components/_cta-banner.scss
  src/components/global/gravity-cta.njk
  src/components/service-cta.njk
  src/posts/2025-03-19-gravity.md
  static/assets/images/posts/2025-03-19-gravity/approval-page.mp4
  static/assets/images/posts/2025-03-19-gravity/approved.png
  static/assets/images/posts/2025-03-19-gravity/automatically-approved.png
  static/assets/images/posts/2025-03-19-gravity/gravity-diagram.svg
  static/assets/images/posts/2025-03-19-gravity/header-image.webp
  static/assets/images/posts/2025-03-19-gravity/needs-approval.png
  static/assets/images/posts/2025-03-19-gravity/og-image.jpg
Labels: blog post
